#!/bin/sh

unamestr=`uname -s`

case "${unamestr}" in
	Linux*)     machine=Linux;;
	Darwin*)    machine=Mac;;
	FreeBSD*)    machine=Mac;;
esac

# Platform specific 
# Linux
if [[ "$unamestr" == 'Linux' ]]; then
    alias rewifi='nmcli nm wifi off && nmcli nm wifi on'
	alias bashrc='vim ~/.bashrc'
 	alias sourcebashrc='source ~/.bashrc'
# Mac OS X
elif [[ "$unamestr" == 'FreeBSD' || "$unamestr" == 'Darwin' ]]; then
    alias timestamp='date +%s | pbcopy; echo "Timestamp copied to clipboard"; date +%s;'
    alias md='open -a MacDown'
	alias bashrc='vim ~/.bash_profile'
 	alias sourcebashrc='source ~/.bash_profile'
fi

 # Personal aliases
 alias vimrc='vim ~/.vimrc'
 
 alias cdhome='cd ~/'
 alias cdgoarashout='cd $GOPATH/src/github.com/arashout'

###########################################################################
# Very handy tweaks
###

alias chmox='chmod +x'
alias schmox='sudo chmod +x'

# this one saved by butt so many times
alias wget='wget -c' # resumes downloads by default

# git shortcuts
alias gs='git status'
alias gc='git commit -m'
alias gca='git commit -a -m'
alias gp='git push' 
alias ga.='git add .'
alias gd='git diff'
alias gch='git checkout'

# docker shortcuts
alias dp='docker ps'
alias dpa='docker ps -a'
alias dstatus='docker-compose exec dev supervisorctl status'
alias dlog='docker-compose logs dev'
alias dstopall='docker stop $(docker ps -aq)'
